In [1]:
import numpy as np
from scipy import sparse
import matplotlib.pyplot as plt
import pandas as pd
import IPython
import sklearn
import seaborn as sns

In [2]:
#Import train dataset:
train = pd.read_csv('train.csv', header=0, sep=',', encoding='utf-8')
train.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266  ...   4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338  ...   7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155  ...   2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250  ...   4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

In [3]:
train.set_index('ID_code', inplace=True)
train.head()

target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
ID_code                                                                      
train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

           var_7   var_8  ...  var_190  var_191  var_192  var_193  var_194  \
ID_code                   ...                                                
train_0  18.6266 -4.9200  ...   4.4354   3.9642   3.1364   1.6910  18.5227   
train_1  16.5338  3.1468  ...   7.6421   7.7214   2.5837  10.9516  15.4305   
train_2  14.6155 -4.9193  ...   2.9057   9.7905   1.6704   1.6858  21.6042   
train_3  14.9250 -5.8609  ...   4.4666   4.7433   0.7178   1.4214  23.0347   
train_4  19.2514  6.2654  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876   

         var_195  var_196  var_197  var_198  var_199  
ID_code                                               
train_0  -2.3978   7.8784   8.5635  12.7803  -1.0914  
train_1   2.0339   8.1267   8.7889  18.3560   1.9518  
train_2   3.1417  -6.5213   8.2675  14.7222   0.3965  
train_3  -1.2706  -2.9275  10.2922  17.9697  -8.9996  
train_4  -1.5121   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 201 columns]

In [4]:
#see balance of target:
train['target'].value_counts()

0    179902
1     20098
Name: target, dtype: int64

In [5]:
import random
random.seed(30)
train0 = train.loc[train['target'] == 0]
train_0 = train0.sample(20098)
train_1 = train.loc[train['target'] == 1]

In [6]:
train_0['target'].value_counts()

0    20098
Name: target, dtype: int64

In [7]:
train_1['target'].value_counts()

1    20098
Name: target, dtype: int64

In [8]:
#We add both so that we have our balance train dataset:
frames = [train_0, train_1]
train_balanced = pd.concat(frames)
train_balanced['target'].value_counts()

1    20098
0    20098
Name: target, dtype: int64

In [9]:
#Let's create a small subset to train our model:
train_0_sample = train_0.sample(1000)
train_1_sample = train_1.sample(1000)
samples = [train_0_sample, train_1_sample]
train_sample = pd.concat(samples)

In [10]:
train_sample['target'].value_counts()

1    1000
0    1000
Name: target, dtype: int64

In [11]:
train_sample.head()

target    var_0   var_1    var_2   var_3    var_4    var_5  \
ID_code                                                                   
train_69152       0  15.5690 -4.4441   7.4087  8.4474  12.1037 -15.4558   
train_50923       0   7.8228  0.9865   7.6627  9.7049  11.3241   0.5561   
train_75263       0   9.3890 -9.5473  11.8015  8.1886   8.4587 -16.9507   
train_73609       0  12.2668 -6.5051  12.0209  9.6434  12.3136   2.1052   
train_48253       0  11.4436 -6.3961   7.8527  6.0147  12.8791  -7.5009   

              var_6    var_7   var_8  ...  var_190  var_191  var_192  var_193  \
ID_code                               ...                                       
train_69152  4.8109  12.3361 -2.6722  ...   6.2854   9.9992   0.0726   4.7458   
train_50923  5.0783   9.7708  1.5730  ...  -2.8172  10.6039   3.0071   1.2855   
train_75263  5.6968  17.2991 -4.3091  ...   4.9663   5.5662   2.6519   5.5111   
train_73609  5.3094  13.8643 -3.5726  ...   7.2674   6.4485   1.7669   8.7936   
train_48253  3.8588  19.4187 -4.0940  ...   6.0044   7.4941   0.8984  -1.0692   

             var_194  var_195  var_196  var_197  var_198  var_199  
ID_code                                                            
train_69152  17.6313   0.1727  -0.0458   9.2814  15.9298   4.4416  
train_50923  16.7897  -0.8709  -3.4372   9.5069  12.2323  -7.1834  
train_75263  20.7882  -0.8539  -1.6310   7.9749  17.9573  -6.2334  
train_73609  19.1152  -0.3217   4.7470   9.9318   8.6279   4.5193  
train_48253  16.6193   1.3050   5.4583   6.9691   8.0637   5.8145  

[5 rows x 201 columns]

In [24]:
#Create X matrix and y array in sample:
X = train_sample.iloc[:,1:].values
y = train_sample.iloc[:,0].values

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [37]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

In [38]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test) 

In [39]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(max_depth=2, random_state=0)

classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test) 

/home/ainhoa/anaconda3/envs/kschool/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [40]:
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[155  45]
 [ 71 129]]
Accuracy0.71


In [41]:
X_train.shape

(1600, 1)

In [43]:
y_train.reshape(1600,1)

array([[0],
       [0],
       [1],
       ...,
       [1],
       [0],
       [0]])

In [45]:
y_train.shape

(1600,)

In [46]:
train.head()

target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
ID_code                                                                      
train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

           var_7   var_8  ...  var_190  var_191  var_192  var_193  var_194  \
ID_code                   ...                                                
train_0  18.6266 -4.9200  ...   4.4354   3.9642   3.1364   1.6910  18.5227   
train_1  16.5338  3.1468  ...   7.6421   7.7214   2.5837  10.9516  15.4305   
train_2  14.6155 -4.9193  ...   2.9057   9.7905   1.6704   1.6858  21.6042   
train_3  14.9250 -5.8609  ...   4.4666   4.7433   0.7178   1.4214  23.0347   
train_4  19.2514  6.2654  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876   

         var_195  var_196  var_197  var_198  var_199  
ID_code                                               
train_0  -2.3978   7.8784   8.5635  12.7803  -1.0914  
train_1   2.0339   8.1267   8.7889  18.3560   1.9518  
train_2   3.1417  -6.5213   8.2675  14.7222   0.3965  
train_3  -1.2706  -2.9275  10.2922  17.9697  -8.9996  
train_4  -1.5121   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 201 columns]

In [48]:
#Now let's do the predictions in the whole dataset:
X = train.iloc[:,1:].values
y = train.iloc[:,0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)  

In [49]:
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

In [50]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=1)  
X_train = lda.fit_transform(X_train, y_train)  
X_test = lda.transform(X_test) 

In [51]:
classifier.fit(X_train, y_train)  
y_pred = classifier.predict(X_test)

In [52]:
cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy' + str(accuracy_score(y_test, y_pred))) 

[[35544   442]
 [ 2994  1020]]
Accuracy0.9141


Now: let's predict with the real test dataset and generate the submission file

In [53]:
#Import test dataset:
test = pd.read_csv('test.csv', header=0, sep=',', encoding='utf-8')
test.head()

ID_code    var_0    var_1    var_2   var_3    var_4   var_5   var_6  \
0  test_0  11.0656   7.7798  12.9536  9.4292  11.4327 -2.3805  5.8493   
1  test_1   8.5304   1.2543  11.3047  5.1858   9.1974 -4.0117  6.0196   
2  test_2   5.4827 -10.3581  10.1407  7.0479  10.2628  9.8052  4.8950   
3  test_3   8.5374  -1.3222  12.0220  6.5749   8.8458  3.1744  4.9397   
4  test_4  11.7058  -0.1327  14.1295  7.7506   9.1035 -8.5848  6.8595   

     var_7   var_8  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.2675  2.1337  ...  -2.1556  11.8495  -1.4300   2.4508  13.7112   2.4669   
1  18.6316 -4.4131  ...  10.6165   8.8349   0.9403  10.1282  15.5765   0.4773   
2  20.2537  1.5233  ...  -0.7484  10.9935   1.9803   2.1800  12.9813   2.1281   
3  20.5660  3.3755  ...   9.5702   9.0766   1.6580   3.5813  15.1874   3.1656   
4  10.6048  2.9890  ...   4.2259   9.1723   1.2835   3.3778  19.5542  -0.2860   

   var_196  var_197  var_198  var_199  
0   4.3654  10.7200  15.4722  -8.7197  
1  -1.4852   9.8714  19.1293 -20.9760  
2  -7.1086   7.0618  19.8956 -23.1794  
3   3.9567   9.2295  13.0168  -4.2108  
4  -5.1612   7.2882  13.9260  -9.1846  

[5 rows x 201 columns]

In [54]:
test.set_index('ID_code', inplace=True)
test.head()

var_0    var_1    var_2   var_3    var_4   var_5   var_6    var_7  \
ID_code                                                                        
test_0   11.0656   7.7798  12.9536  9.4292  11.4327 -2.3805  5.8493  18.2675   
test_1    8.5304   1.2543  11.3047  5.1858   9.1974 -4.0117  6.0196  18.6316   
test_2    5.4827 -10.3581  10.1407  7.0479  10.2628  9.8052  4.8950  20.2537   
test_3    8.5374  -1.3222  12.0220  6.5749   8.8458  3.1744  4.9397  20.5660   
test_4   11.7058  -0.1327  14.1295  7.7506   9.1035 -8.5848  6.8595  10.6048   

          var_8   var_9  ...  var_190  var_191  var_192  var_193  var_194  \
ID_code                  ...                                                
test_0   2.1337  8.8100  ...  -2.1556  11.8495  -1.4300   2.4508  13.7112   
test_1  -4.4131  5.9739  ...  10.6165   8.8349   0.9403  10.1282  15.5765   
test_2   1.5233  8.3442  ...  -0.7484  10.9935   1.9803   2.1800  12.9813   
test_3   3.3755  7.4578  ...   9.5702   9.0766   1.6580   3.5813  15.1874   
test_4   2.9890  7.1437  ...   4.2259   9.1723   1.2835   3.3778  19.5542   

         var_195  var_196  var_197  var_198  var_199  
ID_code                                               
test_0    2.4669   4.3654  10.7200  15.4722  -8.7197  
test_1    0.4773  -1.4852   9.8714  19.1293 -20.9760  
test_2    2.1281  -7.1086   7.0618  19.8956 -23.1794  
test_3    3.1656   3.9567   9.2295  13.0168  -4.2108  
test_4   -0.2860  -5.1612   7.2882  13.9260  -9.1846  

[5 rows x 200 columns]

In [59]:
X = test.iloc[:,0:].values

In [61]:
sc = MinMaxScaler()
X_test = sc.fit_transform(X) 

In [62]:
X_test = lda.transform(X_test)

In [63]:
y_pred = classifier.predict(X_test)

In [64]:
pd.DataFrame(y_pred).to_csv('prediction_v4.csv')

The result of this submission with the new data is 0.617